[package]
name = "kunit"
version = "0.1.0"
edition = "2024"

[dependencies]
conquer-once = { version = "0.4.0", default-features =  false }
heapless = "0.9.1"
ktest-macros = "0.1.2"
spin = "0.10.0"

[target.'cfg(target_arch = "x86_64")'.dependencies]
x86_64 = "0.15.4"
uart_16550 = "0.4.0"